import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ar' | 'ku';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'Inventory Management System',
    'nav.dashboard': 'Dashboard',
    'nav.products': 'Products',
    'nav.sales': 'Sales',
    'nav.returns': 'Returns',
    'nav.reports': 'Reports',
    'nav.advancedReports': 'Advanced Reports',
    'nav.sellers': 'Seller Reports',
    'nav.users': 'Users',
    'nav.mobile': 'Mobile Sync',
    'nav.settings': 'Settings',
    'nav.notifications': 'Notifications',
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'product.name': 'Product Name',
    'product.sku': 'SKU',
    'product.price': 'Price',
    'product.cost': 'Cost',
    'product.stock': 'Stock',
    'product.category': 'Category',
    'product.addProduct': 'Add Product',
    'product.editProduct': 'Edit Product',
    'sale.recordSale': 'Record Sale',
    'sale.customer': 'Customer',
    'sale.total': 'Total',
    'sale.date': 'Date',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.totalSales': 'Total Sales',
    'dashboard.lowStock': 'Low Stock Items',
    'dashboard.outOfStock': 'Out of Stock',
  },
  es: {
    'app.title': 'Sistema de Gestión de Inventario',
    'nav.dashboard': 'Panel',
    'nav.products': 'Productos',
    'nav.sales': 'Ventas',
    'nav.returns': 'Devoluciones',
    'nav.reports': 'Informes',
    'nav.advancedReports': 'Informes Avanzados',
    'nav.sellers': 'Informes de Vendedores',
    'nav.users': 'Usuarios',
    'nav.mobile': 'Sincronización Móvil',
    'nav.settings': 'Configuración',
    'nav.notifications': 'Notificaciones',
    'auth.login': 'Iniciar Sesión',
    'auth.logout': 'Cerrar Sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'common.add': 'Agregar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.loading': 'Cargando...',
    'common.noData': 'No hay datos disponibles',
    'product.name': 'Nombre del Producto',
    'product.sku': 'SKU',
    'product.price': 'Precio',
    'product.cost': 'Costo',
    'product.stock': 'Inventario',
    'product.category': 'Categoría',
    'product.addProduct': 'Agregar Producto',
    'product.editProduct': 'Editar Producto',
    'sale.recordSale': 'Registrar Venta',
    'sale.customer': 'Cliente',
    'sale.total': 'Total',
    'sale.date': 'Fecha',
    'dashboard.totalRevenue': 'Ingresos Totales',
    'dashboard.totalSales': 'Ventas Totales',
    'dashboard.lowStock': 'Artículos con Bajo Inventario',
    'dashboard.outOfStock': 'Sin Existencias',
  },
  fr: {
    'app.title': 'Système de Gestion des Stocks',
    'nav.dashboard': 'Tableau de Bord',
    'nav.products': 'Produits',
    'nav.sales': 'Ventes',
    'nav.returns': 'Retours',
    'nav.reports': 'Rapports',
    'nav.advancedReports': 'Rapports Avancés',
    'nav.sellers': 'Rapports des Vendeurs',
    'nav.users': 'Utilisateurs',
    'nav.mobile': 'Synchronisation Mobile',
    'nav.settings': 'Paramètres',
    'nav.notifications': 'Notifications',
    'auth.login': 'Connexion',
    'auth.logout': 'Déconnexion',
    'auth.signup': "S'inscrire",
    'auth.email': 'Email',
    'auth.password': 'Mot de Passe',
    'common.add': 'Ajouter',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.loading': 'Chargement...',
    'common.noData': 'Aucune donnée disponible',
    'product.name': 'Nom du Produit',
    'product.sku': 'SKU',
    'product.price': 'Prix',
    'product.cost': 'Coût',
    'product.stock': 'Stock',
    'product.category': 'Catégorie',
    'product.addProduct': 'Ajouter un Produit',
    'product.editProduct': 'Modifier le Produit',
    'sale.recordSale': 'Enregistrer une Vente',
    'sale.customer': 'Client',
    'sale.total': 'Total',
    'sale.date': 'Date',
    'dashboard.totalRevenue': 'Revenu Total',
    'dashboard.totalSales': 'Ventes Totales',
    'dashboard.lowStock': 'Articles en Rupture',
    'dashboard.outOfStock': 'Rupture de Stock',
  },
  de: {
    'app.title': 'Lagerverwaltungssystem',
    'nav.dashboard': 'Dashboard',
    'nav.products': 'Produkte',
    'nav.sales': 'Verkäufe',
    'nav.returns': 'Rücksendungen',
    'nav.reports': 'Berichte',
    'nav.advancedReports': 'Erweiterte Berichte',
    'nav.sellers': 'Verkäuferberichte',
    'nav.users': 'Benutzer',
    'nav.mobile': 'Mobile Synchronisation',
    'nav.settings': 'Einstellungen',
    'nav.notifications': 'Benachrichtigungen',
    'auth.login': 'Anmelden',
    'auth.logout': 'Abmelden',
    'auth.signup': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'common.add': 'Hinzufügen',
    'common.edit': 'Bearbeiten',
    'common.delete': 'Löschen',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.export': 'Exportieren',
    'common.import': 'Importieren',
    'common.loading': 'Laden...',
    'common.noData': 'Keine Daten verfügbar',
    'product.name': 'Produktname',
    'product.sku': 'SKU',
    'product.price': 'Preis',
    'product.cost': 'Kosten',
    'product.stock': 'Bestand',
    'product.category': 'Kategorie',
    'product.addProduct': 'Produkt Hinzufügen',
    'product.editProduct': 'Produkt Bearbeiten',
    'sale.recordSale': 'Verkauf Erfassen',
    'sale.customer': 'Kunde',
    'sale.total': 'Gesamt',
    'sale.date': 'Datum',
    'dashboard.totalRevenue': 'Gesamtumsatz',
    'dashboard.totalSales': 'Gesamtverkäufe',
    'dashboard.lowStock': 'Niedrige Lagerbestände',
    'dashboard.outOfStock': 'Nicht Vorrätig',
  },
  zh: {
    'app.title': '库存管理系统',
    'nav.dashboard': '仪表板',
    'nav.products': '产品',
    'nav.sales': '销售',
    'nav.returns': '退货',
    'nav.reports': '报告',
    'nav.advancedReports': '高级报告',
    'nav.sellers': '销售报告',
    'nav.users': '用户',
    'nav.mobile': '移动同步',
    'nav.settings': '设置',
    'nav.notifications': '通知',
    'auth.login': '登录',
    'auth.logout': '登出',
    'auth.signup': '注册',
    'auth.email': '电子邮件',
    'auth.password': '密码',
    'common.add': '添加',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.export': '导出',
    'common.import': '导入',
    'common.loading': '加载中...',
    'common.noData': '无数据',
    'product.name': '产品名称',
    'product.sku': 'SKU',
    'product.price': '价格',
    'product.cost': '成本',
    'product.stock': '库存',
    'product.category': '类别',
    'product.addProduct': '添加产品',
    'product.editProduct': '编辑产品',
    'sale.recordSale': '记录销售',
    'sale.customer': '客户',
    'sale.total': '总计',
    'sale.date': '日期',
    'dashboard.totalRevenue': '总收入',
    'dashboard.totalSales': '总销售额',
    'dashboard.lowStock': '低库存商品',
    'dashboard.outOfStock': '缺货',
  },
  ar: {
    'app.title': 'نظام إدارة المخزون',
    'nav.dashboard': 'لوحة التحكم',
    'nav.products': 'المنتجات',
    'nav.sales': 'المبيعات',
    'nav.returns': 'المرتجعات',
    'nav.reports': 'التقارير',
    'nav.advancedReports': 'تقارير متقدمة',
    'nav.sellers': 'تقارير البائعين',
    'nav.users': 'المستخدمون',
    'nav.mobile': 'المزامنة المحمولة',
    'nav.settings': 'الإعدادات',
    'nav.notifications': 'الإشعارات',
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.signup': 'التسجيل',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'common.add': 'إضافة',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.loading': 'جاري التحميل...',
    'common.noData': 'لا توجد بيانات',
    'product.name': 'اسم المنتج',
    'product.sku': 'رمز SKU',
    'product.price': 'السعر',
    'product.cost': 'التكلفة',
    'product.stock': 'المخزون',
    'product.category': 'الفئة',
    'product.addProduct': 'إضافة منتج',
    'product.editProduct': 'تعديل المنتج',
    'sale.recordSale': 'تسجيل عملية بيع',
    'sale.customer': 'العميل',
    'sale.total': 'المجموع',
    'sale.date': 'التاريخ',
    'dashboard.totalRevenue': 'إجمالي الإيرادات',
    'dashboard.totalSales': 'إجمالي المبيعات',
    'dashboard.lowStock': 'عناصر منخفضة المخزون',
    'dashboard.outOfStock': 'نفذ من المخزون',
  },
  ku: {
    'app.title': 'سیستەمی بەڕێوەبردنی کۆگا',
    'nav.dashboard': 'داشبۆرد',
    'nav.products': 'پارچەکان',
    'nav.sales': 'فرۆشتن',
    'nav.returns': 'گەڕاندنەوە',
    'nav.reports': 'ڕاپۆرتەکان',
    'nav.advancedReports': 'ڕاپۆرتی پێشکەوتوو',
    'nav.sellers': 'ڕاپۆرتی فرۆشیاران',
    'nav.users': 'بەکارهێنەران',
    'nav.mobile': 'هاوکاتکردنی مۆبایل',
    'nav.settings': 'ڕێکخستنەکان',
    'nav.notifications': 'ئاگادارکردنەوەکان',
    'auth.login': 'چوونەژوورەوە',
    'auth.logout': 'چوونەدەرەوە',
    'auth.signup': 'تۆمارکردن',
    'auth.email': 'ئیمەیڵ',
    'auth.password': 'وشەی نهێنی',
    'common.add': 'زیادکردن',
    'common.edit': 'دەستکاریکردن',
    'common.delete': 'سڕینەوە',
    'common.save': 'پاشەکەوتکردن',
    'common.cancel': 'هەڵوەشاندنەوە',
    'common.search': 'گەڕان',
    'common.filter': 'پاڵاوتن',
    'common.export': 'هەناردەکردن',
    'common.import': 'هاوردەکردن',
    'common.loading': 'بارکردن...',
    'common.noData': 'هیچ زانیاریەک نییە',
    'product.name': 'ناوی بەرهەم',
    'product.sku': 'کۆدی بەرهەم',
    'product.price': 'نرخ',
    'product.cost': 'تێچوون',
    'product.stock': 'کۆگا',
    'product.category': 'جۆر',
    'product.addProduct': 'زیادکردنی بەرهەم',
    'product.editProduct': 'دەستکاریکردنی بەرهەم',
    'sale.recordSale': 'تۆمارکردنی فرۆشتن',
    'sale.customer': 'کڕیار',
    'sale.total': 'کۆی گشتی',
    'sale.date': 'بەروار',
    'dashboard.totalRevenue': 'کۆی گشتی داهات',
    'dashboard.totalSales': 'کۆی گشتی فرۆشتن',
    'dashboard.lowStock': 'کۆگای کەم',
    'dashboard.outOfStock': 'کۆگا بەتاڵە',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = (language === 'ar' || language === 'ku') ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export const languages: { code: Language; name: string; flag: string }[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'ku', name: 'کوردی', flag: '🟥🟩' },
];
